SOURCES_CXX_CORE := $(CORE_DIR)/../core/Decoder.cpp $(CORE_DIR)/../core/Disassembler.cpp $(CORE_DIR)/../core/KeyStatus.cpp $(CORE_DIR)/../core/PD777.cpp $(CORE_DIR)/../core/PD777Config.cpp $(CORE_DIR)/../core/PD777Graphics.cpp $(CORE_DIR)/../core/rom.cpp $(CORE_DIR)/../core/romSetup.cpp $(CORE_DIR)/../core/Stack.cpp

SOURCES_CXX_CATLIB := $(CORE_DIR)/cat/catAudio.cpp

SOURCES_CXX := $(CORE_DIR)/libretro.cpp $(CORE_DIR)/LibretroPD777.cpp $(SOURCES_CXX_CORE) $(SOURCES_CXX_CATLIB)
